### ISSUE TITLE
install_dependencies.sh problem

### ISSUE THREAD

**Issue by andrew16180** [tdicola/creepyportrait#7]
I am a total novice. I've followed the instructions for the creepyportrait and get to the final instruction and then get the following:

pi@raspberrypi ~/creepyportrait $ sudo ./install_dependencies.sh
inserting gstreamer 1.0 repository
updating apt database
Get:1 http://mirrordirector.raspbian.org jessie InRelease [15.0 kB]
Ign http://vontaene.de . InRelease  
Get:2 http://archive.raspberrypi.org jessie InRelease [13.3 kB]  
Get:3 http://vontaene.de . Release.gpg [198 B]  
Get:4 http://mirrordirector.raspbian.org jessie/main armhf Packages [8,962 kB]
Hit http://vontaene.de . Release  
Get:5 http://archive.raspberrypi.org jessie/main Sources [25.8 kB]
Ign http://vontaene.de . Release  
Hit http://archive.raspberrypi.org jessie/ui Sources  
Get:6 http://archive.raspberrypi.org jessie/main armhf Packages [67.4 kB]  
Hit http://archive.raspberrypi.org jessie/ui armhf Packages  
Get:7 http://mirrordirector.raspbian.org jessie/contrib armhf Packages [37.4 kB]
Get:8 http://mirrordirector.raspbian.org jessie/non-free armhf Packages [70.2 kB]
Get:9 http://mirrordirector.raspbian.org jessie/rpi armhf Packages [1,356 B]  
Hit http://vontaene.de ./main armhf Packages  
Ign http://vontaene.de ./main Translation-en_GB  
Ign http://vontaene.de ./main Translation-en  
Ign http://archive.raspberrypi.org jessie/main Translation-en_GB  
Ign http://archive.raspberrypi.org jessie/main Translation-en  
Ign http://archive.raspberrypi.org jessie/ui Translation-en_GB  
Ign http://archive.raspberrypi.org jessie/ui Translation-en  
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_GB  
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en  
Ign http://mirrordirector.raspbian.org jessie/main Translation-en_GB  
Ign http://mirrordirector.raspbian.org jessie/main Translation-en  
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_GB  
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en  
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_GB  
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en  
Fetched 9,192 kB in 35s (261 kB/s)  
Reading package lists... Done
W: GPG error: http://vontaene.de . Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F0DAA5410C667A3E
installing OF dependencies
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Note, selecting 'libsndfile1-dev' instead of 'libsndfile-dev'
alsa-base is already the newest version.
alsa-base set to manually installed.
alsa-utils is already the newest version.
g++ is already the newest version.
g++ set to manually installed.
libfreetype6-dev is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-argparse : Depends: python2.6 but it is not installable
E: Unable to correct problems, you have held broken packages.
error installing dependencies, there could be an error with your internet connection
if the error persists, please report an issue in github: http://github.com/openframeworks/openFrameworks/issues

Very grateful for any help you can give me. Thank you. A.

**Comment by nik849** [comment]
This has happened to me, since python2.7 arg-parse is included, and your standard python distribution(2.7) will have it.  The fix here is to remove the dependency in the shell script.  I'll do it now, hopefully it should solve the issue.

**Comment by nik849** [comment]
Oh wow, sorry just seen the date on this!  I guess you have solved it, stumbled across this!

**Comment by andrew16180** [comment]
Nick thanks for the message - yes we fixed it. Thanks again, Andrew

**Comment by DavidBates** [comment]
@andrew16180 This is still an issue in the binary linked from Adafruit. Might want to either update the link to a new fixed binary or if you want to support older versions first then a note in the readme would be helpful. Thanks for this great contribution.

**Comment by fscii** [comment]
@DavidBates correct - that's how I just got here by this bombing out:
mkdir ~/creepyportrait
cd ~/creepyportrait
wget https://github.com/tdicola/creepyportrait/raw/master/creepyportrait_1.0_raspberrypi.tar.gz
tar xvf creepyportrait_1.0_raspberrypi.tar.gz
sudo ./install_dependencies.sh

I had to fix the url but what about the dependencies its no longer required?  Sorry I just want to give it a go.

Here's what I got

mkdir: cannot create directory ‘/home/pi/creepyportrait’: File exists
--2018-07-06 22:46:47--  https://github.com/tdicola/creepyportrait/blob/master/creepyportrait_1.0_raspberrypi.tar.gz
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘creepyportrait_1.0_raspberrypi.tar.gz’

creepyportrait_1.0_     [ <=>                ]  38.28K  --.-KB/s    in 0.04s   

2018-07-06 22:46:48 (860 KB/s) - ‘creepyportrait_1.0_raspberrypi.tar.gz’ saved [39197]


gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
sudo: ./install_dependencies.sh: command not found
